### ISSUE TITLE
Change the git repository in the readme on the code page from juho-p to this git

### ISSUE THREAD

**Issue by laxamar** [paolo-sz/fatty#3]
Just a cosmetic change. The file readme.md still refers to the juho-p git.

You might want to change the reference to:

https://github.com/paolo-sz/fatty.git

even if you want to keep the reference to the original

**Comment by paolo-sz** [comment]
Make sense, thanks.

...even if it was a test... just to see if you really know what are you doing... and, also, I'm used to never read instructions... ;-)

**Comment by laxamar** [comment]
> I'm used to never read instructions

I have no idea what you are talking about. I have never, ever, EVER, missed reading all docs from start to finish twice just to be sure. Cause that's just the type of responsible developer I am.
